spring.application.name=coup

# Server settings
server.port=${PORT:8080}

# Database Configuration (PostgreSQL / Supabase)
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.afkfafgnxrgilrzmmowk
spring.datasource.password=f$./2YYUx7s!Kdc
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
